apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qtmrk1x0f-nodejs 
  janus-idp.io/tekton: qtmrk1x0f-nodejs
  backstage.io/kubernetes-id: qtmrk1x0f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qtmrk1x0f-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml