apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qtmrk1x0f-nodejs-gitops
  description: This is GitOps manifest for qtmrk1x0f-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=qtmrk1x0f-nodejs
    backstage.io/kubernetes-id: qtmrk1x0f-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qtmrk1x0f-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qtmrk1x0f-nodejs
