apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qtmrk1x0f-nodejs
  janus-idp.io/tekton: qtmrk1x0f-nodejs
  backstage.io/kubernetes-id: qtmrk1x0f-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qtmrk1x0f-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
